# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #     vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - vendor

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable:
    # Sorted alphabetically.
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    # - cyclop # Disabled length/complexity linters.
    # - deadcode # Replaced by unused.
    - decorder
    # - depguard # Enable with settings for required guards.
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct # Enable for certain files if needed.
    - exportloopref
    # - forbidigo # Enable with settings for required guards.
    - forcetypeassert
    # - funlen # Disabled length/complexity linters.
    # - gci # Using goimports instead.
    # - ginkgolinter # Enable if using Ginkgo.
    - gocheckcompilerdirectives
    # - gochecknoglobals # Useful in some cases.
    # - gochecknoinits # Useful in some cases.
    # - gocognit # Disabled length/complexity linters.
    - goconst
    - gocritic
    # - gocyclo # Disabled length/complexity linters.
    - godot
    - godox
    # - goerr113 # No way to feasibly follow this in many cases.
    # - gofmt # Using gofumpt instead.
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    # - gomodguard # Enable with settings for required guards.
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    # - ifshort # Deprecated.
    - importas
    - ineffassign
    - interfacebloat
    - ireturn # Required for kitlog wrapper.
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    # - prealloc # Unnessesary.
    - predeclared
    - promlinter
    - reassign
    - revive
    # - rowserrcheck # Disabled because of generics.
    - sqlclosecheck # Disabled because of generics.
    - staticcheck
    # - structcheck # Replaced by unused.
    - stylecheck
    # - tagliatelle # Enable if standards are known.
    - tenv
    - testableexamples
    # - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varcheck # Replaced by unused.
    # - varnamelen # Disabled length/complexity linters.
    # - wastedassign # Disabled because of generics.
    - whitespace
    - wrapcheck
    # - wsl # Way too annoying to deal with.

linters-settings:
  misspell:
    locale: US

  exhaustive:
    default-signifies-exhaustive: true

  goimports:
    local-prefixes: github.com/MacroPower/twitch_predictions_recorder

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - promlinter

    - source: ^(\s+)log\..+\.Log\(
      linters:
        - errcheck

    - source: '[ ](log\.)?Logger[ ]'
      linters:
        - ireturn

    - source: '.+\.WriteString\(`\{.+'
      linters:
        - lll

    - source: 'type Event.*'
      linters:
        - revive
