name: benchdiff-pr

on:
  pull_request:

jobs:
  benchdiff:
    name: bench
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set vars
        id: vars
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Run benchdiff
        uses: WillAbides/benchdiff-action@v0
        with:
          benchdiff_version: 0.7.1
          status_name: text-bench-result
          status_sha: ${{ steps.vars.outputs.sha }}
          status_on_degraded: neutral
          benchdiff_args: |
            --base-ref=origin/main
            --cpu=1,2
            --count=5
            --warmup-count=1
            --tolerance=30
            --benchmem
            --debug
