name: go-test

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.20.x']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Go test
        run: make go-test-action
